### ISSUE TITLE
policies respect global hooks

### ISSUE THREAD

**Issue by bingtsingw** [adonisjs/bouncer#10]
```javascript
// start/bouncer.ts
Bouncer.before((user: User | null) => {
  console.log('before hook');
});

export const { policies } = Bouncer.registerPolicies({
  TestPolicy: () => import('xxx'),
});
```

`await bouncer.with('TestPolicy').authorize('xx');` would not invoke the before hook. If I have multiple policies, are there any way to have global hooks for all policies

**Comment by thetutlage** [comment]
This is designed to work in this way. If you want shared hooks, you can create a base policy class and then `before` hook on that.

**Comment by bingtsingw** [comment]
That's true, but do you have interest to add a `Boolean` property such as `useGlobalHooks` in `BasePolicy` to toggle this feature?
I can help to send a pr.
