### ISSUE TITLE
Does Bounce.ability support asynchronous functions?

### ISSUE THREAD

**Issue by h25302** [adonisjs/bouncer#14]
### Package version

6.2.3

### Describe the bug

@adonisjs/core Version: 6.2.3,
@adonisjs/bouncer Version: 3.1.1
typescript Version: 5.3.3

```
export const test = Bouncer.ability(async (user: User, key: string) => {
  if (await permService.hasPerm(user, key)) {
    return true
  }
  return AuthorizationResponse.deny('Page not found')
})
```

An error occurred:
error TS2345: Argument of type '(user: User, key: string) => Promise<true | AuthorizationResponse>' is not assignable to parameter of type 'BouncerAuthorizer<any>'.
Type 'Promise<true | AuthorizationResponse>' is not assignable to type 'AuthorizerResponse'.
    Type 'Promise<true | AuthorizationResponse>' is not assignable to type 'Promise<boolean>'.
      Type 'true | AuthorizationResponse' is not assignable to type 'boolean'.
        Type 'AuthorizationResponse' is not assignable to type 'boolean'.

**Comment by h25302** [comment]
**policies also cannot support asynchronous functions**

```
export default class TestPolicy extends BasePolicy {
  // This is an asynchronous function
  async test(user: User) {
    return await check(user)
  }
}
```

**Errors may occur in the Controller**
```
export default class TestController {
  async getSetting({ bouncer }: HttpContext) {
    // error TS2345: Argument of type '"test"' is not assignable to parameter of type 'GetPolicyMethods<User | (User & { currentAccessToken: AccessToken; }), TestPolicy>'.
    await bouncer.with('TestPolicy').authorize('test')
    return { ok: true }
  }
}
```

**Comment by thetutlage** [comment]
Bouncer does support async functions, your issue is with the `User` type accepted by the `test` function and the `User` type returned by the `auth.user` property.

Check docs for defining the `currentAccessToken` property on the User model here. https://docs.adonisjs.com/guides/auth-access-tokens-guard#the-current-access-token

**Comment by jwahdatehagh** [comment]
still don't think typescript is able to extract the async functions properly. reproduction link: https://github.com/jwahdatehagh/bouncer/commit/14ed06bd6b0abb3f8f369eab28ee64771aafd5f3 

![Image](https://github.com/user-attachments/assets/af331fa3-f364-40e3-82a9-2245d1b0b194)

works fine for sync policies, but when using `denies`, the async policies are not recognized.

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/bouncer/releases/tag/v3.1.6
