### ISSUE TITLE
TypeError at app startup

### ISSUE THREAD

**Issue by romch007** [adonisjs/bouncer#4]
I just installed `@adonisjs/bouncer` and I haven't created no policies or actions yet. When I run `node ace serve` or `node ace migration:status`, I get the following error :

```
TypeError: this.app.container.withBindings is not a function

BouncerServiceProvider.boot
  /home/romain/documents/openotes/node_modules/@adonisjs/bouncer/build/providers/BouncerProvider.js:28
...
```

## Package version
`@adonisjs/core`: 5.0.4-preview-rc-2.1
`@adonisjs/bouncer`: 2.0.0

## Node.js and npm version
node: v14.15.4
yarn: 1.22.10

## Sample Code (to reproduce the issue)
Commands : `yarn add @adonisjs/bouncer` and `node ace invoke @adonisjs/bouncer` then `node ace serve`

**Comment by thetutlage** [comment]
The package targets the next version (v5 out of preview) of the framework. So I recommend waiting for the complete release 🙂

**Comment by thetutlage** [comment]
Will close it for now :)
